import type { AnalysisParams } from "./types";

export const defaultAnalysisParams: AnalysisParams = {
  symbol: "AGQ",
  interval: "1d",
  bbPeriod: 20,
  bbMultiplier: 2,
  rsiPeriod: 14,
  showBollingerBands: false,
  showRsi: false,
  showVolume: false,
  showVolumeProfile: false,
  showVwap: false,
  showAtr: false,
  showIchimoku: false,
  showSupertrend: false,
  showParabolicSar: false,
  market: "usStock",
  smaPeriods: [],
  emaPeriods: [],
  hmaPeriods: [],
  macd: null,
  stochastic: null,
  showObv: false,
  showCvd: false,
  donchian: null,
  keltner: null,
  mfi: null,
  cmf: null,
  choppiness: null,
  williamsR: null,
  adx: null,
  stc: null,
  smc: null,
  anchoredVwap: null,
  autoFib: null,
  signalStrategies: {},
};
